### ISSUE TITLE
Loss function

### ISSUE THREAD

**Issue by Zoigin** [sony/sqvae#4]
Hi，
Your project is very good, but I have a question about the loss function.

<img width="1280" alt="屏幕截图 2023-04-13 183028" src="https://user-images.githubusercontent.com/97080171/231733201-bff76ceb-11c2-4508-8469-6e11e58b1e0d.png">

1.What is the loss expression in 85 row intended to do, or what is its meaning？It provides a negative loss.

Best，
Luoda

**Comment by ytakida** [comment]
Hi Luoda,
Thank you for having an interest in our work!

The loss "kld_discrete" indicates the negative entropy regualaization term for the discrete latent, which corresponds to the third term of Equation (8) in our paper (https://proceedings.mlr.press/v162/takida22a.html).
